/**
 * The MIT License (MIT)
 *
 * MSUSEL Arc Framework
 * Copyright (c) 2015-2019 Montana State University, Gianforte School of Computing,
 * Software Engineering Laboratory and Idaho State University, Informatics and
 * Computer Science, Empirical Software Engineering Laboratory
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ivata_groupware_business_mail_server_HMailServer */

#ifndef _Included_com_ivata_groupware_business_mail_server_HMailServer
#define _Included_com_ivata_groupware_business_mail_server_HMailServer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: class_000240 */
/*
 * Class:     com_ivata_groupware_business_mail_server_HMailServer
 * Method:    getUserAliases
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ivata_groupware_business_mail_server_HMailServer_getUserAliases
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ivata_groupware_business_mail_server_HMailServer
 * Method:    setUserAliases
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ivata_groupware_business_mail_server_HMailServer_setUserAliases
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     com_ivata_groupware_business_mail_server_HMailServer
 * Method:    getVacationMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ivata_groupware_business_mail_server_HMailServer_getVacationMessage
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ivata_groupware_business_mail_server_HMailServer
 * Method:    setVacationMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ivata_groupware_business_mail_server_HMailServer_setVacationMessage
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_ivata_groupware_business_mail_server_HMailServer
 * Method:    addUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ivata_groupware_business_mail_server_HMailServer_addUser
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_ivata_groupware_business_mail_server_HMailServer
 * Method:    checkPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ivata_groupware_business_mail_server_HMailServer_checkPassword
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_ivata_groupware_business_mail_server_HMailServer
 * Method:    isUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ivata_groupware_business_mail_server_HMailServer_isUser
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ivata_groupware_business_mail_server_HMailServer
 * Method:    removeUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ivata_groupware_business_mail_server_HMailServer_removeUser
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ivata_groupware_business_mail_server_HMailServer
 * Method:    setPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ivata_groupware_business_mail_server_HMailServer_setPassword
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
