/**
 * The MIT License (MIT)
 *
 * MSUSEL Arc Framework
 * Copyright (c) 2015-2019 Montana State University, Gianforte School of Computing,
 * Software Engineering Laboratory and Idaho State University, Informatics and
 * Computer Science, Empirical Software Engineering Laboratory
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.geotools.data.ogr.bridj;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : /home/aaime/devel/gdal/gdal-1.8.0/ogr/ogr_core.h:455</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("ogr") 
public class OGREnvelope extends StructObject {
	public OGREnvelope() {
		super();
	}
	public OGREnvelope(Pointer pointer) {
		super(pointer);
	}
	@Field(0) 
	public double MinX() {
		return this.io.getDoubleField(this, 0);
	}
	@Field(0) 
	public OGREnvelope MinX(double MinX) {
		this.io.setDoubleField(this, 0, MinX);
		return this;
	}
	@Field(1) 
	public double MaxX() {
		return this.io.getDoubleField(this, 1);
	}
	@Field(1) 
	public OGREnvelope MaxX(double MaxX) {
		this.io.setDoubleField(this, 1, MaxX);
		return this;
	}
	@Field(2) 
	public double MinY() {
		return this.io.getDoubleField(this, 2);
	}
	@Field(2) 
	public OGREnvelope MinY(double MinY) {
		this.io.setDoubleField(this, 2, MinY);
		return this;
	}
	@Field(3) 
	public double MaxY() {
		return this.io.getDoubleField(this, 3);
	}
	@Field(3) 
	public OGREnvelope MaxY(double MaxY) {
		this.io.setDoubleField(this, 3, MaxY);
		return this;
	}
}
