/**
 * The MIT License (MIT)
 *
 * MSUSEL Arc Framework
 * Copyright (c) 2015-2019 Montana State University, Gianforte School of Computing,
 * Software Engineering Laboratory and Idaho State University, Informatics and
 * Computer Science, Empirical Software Engineering Laboratory
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.finalist.jaggenerator;

/**
 *
 * @author  hillie
 */
public class ConnectView extends javax.swing.JDialog {
   private JagGenerator jg;


   /** Creates new form DTOGenView */
   public ConnectView(JagGenerator jg) {
      this.jg = jg;
      initComponents();
      UrlTextField.setText("jdbc:oracle:thin:@192.168.0.60:1521:sample");
      UsernameTextField.setText("FACTURENONLINE");
      PasswordTextField.setText("FACTURENONLINE");
   }


   public void setUndecorated(boolean val) {
   }


   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   private void initComponents() {//GEN-BEGIN:initComponents
      UrlLabel = new javax.swing.JLabel();
      UsernameLabel = new javax.swing.JLabel();
      PasswordLabel = new javax.swing.JLabel();
      UrlTextField = new javax.swing.JTextField();
      UsernameTextField = new javax.swing.JTextField();
      PasswordTextField = new javax.swing.JTextField();
      ConnectButton = new javax.swing.JButton();

      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
      setUndecorated(true);
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosing(java.awt.event.WindowEvent evt) {
            exitForm(evt);
         }
      });

      UrlLabel.setText("Database URL");
      getContentPane().add(UrlLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, -1));

      UsernameLabel.setText("Username");
      getContentPane().add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, -1));

      PasswordLabel.setText("Password");
      getContentPane().add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

      getContentPane().add(UrlTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 370, -1));

      getContentPane().add(UsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 170, -1));

      getContentPane().add(PasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 170, -1));

      ConnectButton.setText("Connect");
      ConnectButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ConnectButtonActionPerformed(evt);
         }
      });

      getContentPane().add(ConnectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

      pack();
   }//GEN-END:initComponents


   private void ConnectButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConnectButtonActionPerformed
   {//GEN-HEADEREND:event_ConnectButtonActionPerformed
      String url = UrlTextField.getText();
      String username = UsernameTextField.getText();
      String password = PasswordTextField.getText();
      String[] showTableTypes = {"TABLE"};
      jg.setConManager(
            new GenericJdbcManager(url, username, password, jg.root.datasource.getDatabase().getDriverClass(), showTableTypes));
      this.dispose();
   }//GEN-LAST:event_ConnectButtonActionPerformed


   /** Exit the Application */
   private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
      System.exit(-1);
   }//GEN-LAST:event_exitForm


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField UrlTextField;
   private javax.swing.JLabel PasswordLabel;
   private javax.swing.JTextField UsernameTextField;
   private javax.swing.JLabel UrlLabel;
   private javax.swing.JLabel UsernameLabel;
   private javax.swing.JButton ConnectButton;
   private javax.swing.JTextField PasswordTextField;
   // End of variables declaration//GEN-END:variables

}
