//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 05:22:13 PM MST 
//


package edu.montana.gsoc.msusel.patterns.collector.impl.fb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatcherType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatcherType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatcherType")
@XmlSeeAlso({
    FirstVersionMatcherType.class,
    DesignationMatcherType.class,
    OrMatcherType.class,
    PriorityMatcherType.class,
    LocalMatcherType.class,
    RankMatcherType.class,
    MethodMatcherType.class,
    BugCodeMatcherType.class,
    LastVersionMatcherType.class,
    MatchMatcherType.class,
    FieldMatcherType.class,
    TypeMatcherType.class,
    NotMatcherType.class,
    BugMatcherType.class,
    AndMatcherType.class,
    ClassMatcherType.class,
    PackageMatcherType.class,
    BugPatternMatcherType.class
})
public abstract class MatcherType {


}
